app/urls.py
from django.urls import path

from .views import ItemFilterView,ItemDetailView,ItemCreateView,ItemUpdateView,ItemDeleteView


urlpatterns=[
    #一覧画面
    path('',ItemFilterView.as_view(),name='index'),
    #詳細画面
    path('detail/<int:pk>/',ItemDetailView.as_view(),name='detail'),
    #登録画面
    path('create/',ItemCreateView.as_view(),name='create'),
    #更新画面
    path('update/<int:pk>/',ItemUpdateView.as_view(),name='update'),
    #削除画面
    path('delete/<int:pk>/',ItemDeleteView.as_view(),name='delete'),
    ]

project/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('app.urls')),
]

app/models.py
from django.db import models

from django.core import validators



class Item(models.Model):
    SEX_CHOICES=(
        (1,'男性'),
        (2,'女性'),
        )
        
    name=models.CharField(verbose_name='名前',max_length=200,)
    
    age=models.IntegerField(verbose_name='年齢',
                            validators=[validators.MinValueValidator(1)],
                            blank=True,
                            null=True,
                            )
    
    sex=models.IntegerField(verbose_name='性別',choices=SEX_CHOICES,
                            default=1)
    
    memo=models.TextField(verbose_name='備考',max_length=300,
                            blank=True,
                            null=True,
                            )
    
    created_at=models.DateTimeField(verbose_name='登録日',
                                    auto_now_add=True
                                    )
                                    
    #以下は管理サイト上の表示設定
    def __str__(self):
        return self.name
    
    class Meta:
        verbose_name='アイテム'
        verbose_name_plural='アイテム'
                                    

app/forms.py
from django import forms

from .models import Item

class ItemFrom(forms.ModelForm):
    
    class Meta:
        model=Item
        fields=('name','age','sex','memo')
        widgets={
            'name':forms.TextInput(attrs={'placeholder':'記入例:山田　太郎'}),
            'age':forms.NumberInput(attrs={'min':1}),
            'sex':forms.RadioSelect(),
            'memo':forms.Textarea(attrs={'rows':4}),
        }

app/views.py
from django.contrib.auth.mixins import LoginRequiredMixin

from django.urls import reverse_lazy

from django.views.generic import ListView,DetailView

from django.views.generic.edit import CreateView,UpdateView,DeleteView

from django_filters.views import FilterView


from .models import Item

from .filters import ItemFilter

from .forms import ItemFrom



#検索一覧画面
class ItemFilterView(LoginRequiredMixin,FilterView):
    model=Item
    filterset_class=ItemFilter
    
    #デフォルトの並び順を新しい順とする
    queryset=Item.objects.all().order_by('-created_at')
    
    #クエリ未指定の時に全件検索を行うために以下のオプションを指定(django-filter2.0以降）
    strict=False
    
    #1ページ当たりの表示件数
    paginate_by=10
    
    #検索セッションに保存する　or 呼び出す
    def get(self,request,**kwards):
        if request.GET:
            request.session['query']=request.GET
        else:
            request.GET=request.GET.copy()
            if 'query' in request.session.keys():
                for key in request.session['query'].keys():
                    request.GET[key]=request.session['query'][key]
        
        return super().get(request,*kwards)
        
#詳細画面
class ItemDetailView(LoginRequiredMixin,DetailView):
    model=Item
    
#登録画面
class ItemCreateView(LoginRequiredMixin,CreateView):
    model=Item
    form_class=ItemFrom
    success_url=reverse_lazy('index')
    
#更新画面
class ItemUpdateView(LoginRequiredMixin,UpdateView):
    model=Item
    form_class=ItemFrom
    success_url=reverse_lazy('index')
    
#削除画面
class ItemDeleteView(LoginRequiredMixin,DeleteView):
    model=Item
    success_url=reverse_lazy('index')

app/templates/app/_base.html
app/templates/app/_base.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">

<head>
    <!-- Required meta tags always come first -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>アプリケーション名</title>
    <!-- Bootstrap CSS -->
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
        crossorigin="anonymous">
    <link href="{% static "app/css/app.css" %}" rel="stylesheet">
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">アプリケーション名</a>
        <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#Navber" aria-controls="Navber" aria-expanded="false"
            aria-label="ナビゲーションの切替">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="Navber">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'admin:index'%}">管理サイト</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'admin:logout'%}">ログアウト</a>
                </li>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </nav>
    {% block content %} 
    {% endblock %}

    <!-- jQuery first, then Tether, then Bootstrap JS. -->
    <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
        crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <script src="{% static "app/js/plugins/responsive-paginate.js" %}"></script>
    <script src="{% static "app/js/app.js" %}"></script>
</body>

</html>

app/templates/app/_pagination.html
{% load item_extras %}
<ul class="pagination">
    {% if page_obj.has_previous %}
        <li class="page-item pagination-prev">
            <a class="page-link" href-"?{% url_replace request 'page' page_obj.previous_page_number %}">&laquo;</a>
        </li>
    {% else %}
        <li class="disabaled page-item paginate-next">
            <span class="page-link">&laquo;</span>
        </li>
    {% endif %}
    {% for page in page_obj.paginator.page_range %}
        {% if page %}
            {% ifequal page page_obj.number %}
                <li class="active page-item">
                    <span class="page-link">{{page}}
                        <span class="page-link sr-only">(current)</span>
                    </span>
                </li>
            {% else %}
                <li class="page-itme">
                    <a class="page-link" href="?{% url_replace request 'page' page %}">{{page}</a>
                </li>
            {% endifequal %}
        {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
        <li class="page-item pagination-next">
            <a class="page-link" href="?{% url_replace request 'page' page_obj.next_pagenumber %}">&laquo;</a>
        </li>
    {% else %}
        <li class="disabled page-item pagination-next">
            <span class="page-link">&laquo;</span>
        </li>
    {% endif %}
</ul>

app/templates/app/item_card.html
<div class="row">
    <div class="col-3">
        <p>名前</p>
    </div>
    <div class="col-9">
        <p>{{item.name}}</p>
    </div>
</div>
<div class="row">
    <div class="col-3">
        <p>年齢</p>
    </div>
    <div class="col-9">
        <p>{{item.age}}</p>
    </div>
</div>
<div class="row">
    <div class="col-3">
        <p>性別</p>
    </div>
    <div class="col-9">
        <p>{{item.get_sex_display}}</p>
    </div>
</div>
<div class="row">
    <div class="col-3">
        <p>備考</p>
    </div>
    <div class="col-9">
        <p>{{item.memo|linebreaksbr}}</p>
    </div>
</div>
<div class="row">
    <div class="col-3">
        <p>登録日</p>
    </div>
    <div class="col-9">
        <p>{{item.created_at|date:"Y/m/d G:i:s"}}</p>
    </div>
</div>

app/templates/app/item_confirm_delete.html
{% extends "./_base.html" %}

{% block content %}
<div class="container">
    <h2 class="text-center">データ削除</h2>
    <p>このデータを削除します。よろしいですか？</p>
    
    <form action="" method='post'>
        {% csrf_token %}
        <div class="row">
            <div class="col-12">
                <div class="float-right">
                    <a class="btn btn-outline-secondary" href="{% url 'index' %}">戻る</a>
                    <input type="submit" class="btn btn-outline-secondary" value="削除" />
                </div>
            </div>
        </div>
        {% include "./item_card.html" %}
        <div class="row">
            <div class="col-12">
                <div class="float-right">
                    <a class="btn btn-outline-secondary" href="{% url 'index' %}">戻る</a>
                    <input type="submit" class="btn btn-outline-secondary" value="削除" />
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock %}

app/templates/app/item_detail.html
{% extends "./_base.html" %}
{% block content %}
<div class="container">
    <h2 class="text-center">詳細表示</h2>
    <div class="row">
        <div class="col-12">
            <a class="btn btn-outline-secondary float-right" href="{% url 'index' %}">戻る</a>
        </div>
    </div>
    {% include "./item_card.html" %}
    <div class="row">
        <div class="col-12">
            <a class="btn btn-outline-secondary float-right" href="{% url 'index' %}">戻る</a>
        </div>
    </div>
</div>
{% endblock %}

app/templates/app/item_filter.html
{% extends "./_base.html" %}
{% block content %} 
{% load crispy_forms_tags %}
<div class="container">
    <div id="myModal" class="modal fade" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">検索条件</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="閉じる">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <form id="filter" method="get">
                    <div class="modal-body">
                        {{filter.form|crispy}}
                    </div>
                </form>
                <div class="modal-footer">
                    <a class="btn btn-outline-secondary" data-dismiss="modal">戻る</a>
                    <button type="submit" class="btn btn-outline-secondary" form="filter">検索</button>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-12">
            <a class="btn btn-secondary filtered" style="visibility:hidden" href="/?page=1">検索を解除</a>
            <div class="float-right">
                <a class="btn btn-outline-secondary" href="{% url 'create' %}">新規</a>
                <a class="btn btn-outline-secondary" data-toggle="modal" data-target="#myModal" href="#">検索</a>
            </div>
        </div>
    </div>

    <div class="row" >
        <div class="col-12">
            {% include "./_pagination.html" %}
        </div>
    </div>

    <div class="row">
        <div class="col-12">
            <ul class="list-group">
                {% for item in item_list %}
                <li class="list-group-item">
                    <div class="row">
                        <div class="col-3">
                            <p>名前</p>
                        </div>
                        <div class="col-9">
                            <p>{{ item.name }}</p>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-3">
                            <p>登録日</p>
                        </div>
                        <div class="col-9">
                            <p>{{item.created_at|date:"Y/m/d G:i:s"}}</p>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-12">
                            <div class="float-right">
                                <a class="btn btn-outline-secondary " href="{% url 'detail' item.pk %}">詳細</a>
                                <a class="btn btn-outline-secondary " href="{% url 'update' item.pk %}">編集</a>
                                <a class="btn btn-outline-secondary " href="{% url 'delete' item.pk %}">削除</a>
                            </div>
                        </div>
                    </div>
                </li>
                {% empty %}
                <li class="list-group-item">
                    対象のデータがありません
                </li>
                {% endfor %}
            </ul>
        </div>
    </div>
    <div class="row" >
        <div class="col-12">
            <div class="float-right">
                <a class="btn btn-outline-secondary" href="{% url 'create' %}">新規</a>
                <a class="btn btn-outline-secondary" data-toggle="modal" data-target="#myModal" href="#">検索</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

app/templates/app/item_form.html
{% extends "./_base.html" %}
{% load crispy_forms_tags %}
{% block content %}
{{ form.certifications.errors }}
<div class="container">
    <div class="row">
        <div class="col-12">
            <h2 class="text-center">データ入力</h2>
        </div>
    </div>
    <div class="row">
        <div class="col-12">
            <div class="float-right">
                <a class="btn btn-outline-secondary" href="{% url 'index' %}">戻る</a>
                <a class="btn btn-outline-secondary save" href="#">保存</a>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-12">
            <form method="post" id="myform">
                {%crispy form%}
            </form>
        </div>
    </div>
    <div class="row">
        <div class="col-12">
            <div class="float-right">
                <a class="btn btn-outline-secondary" href="{% url 'index' %}">戻る</a>
                <a class="btn btn-outline-secondary save" href="#">保存</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}